addr = "0.0.0.0:9090"
hello_wav = "hello.wav"

[gemini]
api_key = ""

[[gemini.sys_prompts]]
role = "system"
content = """
You are a helpful assistant. Please answer user questions as concise as possible while being accurate and truthful. Use short sentences. Try to be humorous and light-hearted.
"""
